readme.md

Feat: Added basic readme for setup and how to run

---

readme.md

Feat: test

---

Frontend/index.html

I Noticed a major type error in  Project title .I researched the issue and fixed it

Typo: Changed title

---

Frontend/index.html

Title change merging into master

Title change merging into master

---

readme.md

Given a detailed description about the standards and conventions to be followed throughout this project.

Added coding standards to readme

---

Backend/package-lock.json
Backend/package.json
Backend/src/controllers/implementation/auth.controller.ts
Backend/src/controllers/interface/IAuthController.ts
Backend/src/services/implementation/auth.service.ts
Backend/src/services/interface/IAuthService.ts

implemented sign in functionalities in both auth-service and auth-controller.

feat: add sign-in to auth-service and auth-controller

---

Backend/.dockerignore
Frontend/.dockerignore

Feat: added docker ignore

---

Backend/src/repositories/base.repository.ts
Backend/src/repositories/implementation/user.repository.ts

I have added a base repository so that all the repositories can extend it and all the CRUD operations with extras can be reused.

init: Add Base Repository

---

Backend/src/repositories/base.repository.ts
Backend/src/repositories/implementation/user.repository.ts

Feat: pulling changes from dev

---

Backend/src/configs/env.config.ts
Backend/src/configs/redis.config.ts
Backend/src/utils/validate-env.util.ts

#Set up a retry strategy for redis connection in case of connection failure with time limit as well.
#Changed the redis url to host number and port number and stored in the env

Fixed the redis infinite connection retries

---

Backend/package-lock.json
Backend/package.json
Backend/src/configs/env.config.ts
Backend/src/index.ts
Backend/src/services/implementation/auth.service.ts
Backend/src/utils/bcrypt.util.ts
Backend/src/utils/hash-password.util.ts
docker-compose.yaml
package-lock.json

#We were using bcryptjs package and accidentally imported bcrypt package, which led to module not found error
#Created a function to compare the hashed password
#Bcryptjs package was missing in the package-lock.json file
#dotenv package import and config is was changed from the env.config.ts file to index.ts file, because the validateEnv function is getting called before the env is imported

fixed bcrypt package implementation and env load flow

---

.gitignore
frontend/package.json
frontend/src/components/common/Navbar.tsx
package-lock.json

Checked and fixed lint errors and added  package-lock to gitignore.

fix: checked and fixed lint errors and added  package-lock to gitignore

---

frontend/src/components/user/landingPage/FeatureSection.tsx

fix landing page responsive issue in Xl.

fix(ui) : fix landing page responsive issue in Xl

---

frontend/src/components/user/landingPage/FeatureSection.tsx

Fix landing page responsive issue

Fix landing page responsive issue

---

frontend/src/components/user/common/AppSidebar.tsx
frontend/src/router/AppRoutes.tsx

feat: sidebar navigation done

---

backend/package.json
backend/src/constants/response-message.constant.ts
backend/src/controllers/implementation/auth.controller.ts
backend/src/middlewares/validate.middleware.ts
backend/src/routers/auth.router.ts
backend/src/schema/signin.schema.ts
backend/src/schema/signup-schema.ts
backend/src/schema/verify-otp.schema.ts
backend/src/services/implementation/auth.service.ts
backend/src/utils/format-zod-error.util.ts
package-lock.json

This pull request introduces **Zod validation** for request bodies in the backend. The following enhancements have been implemented:
- Added the `zod` package to the project dependencies.
- Implemented a middleware function to handle request body validation using **Zod**.
- Ensured that any request body is validated against the corresponding schema **before reaching the controller**.
- Created a dedicated `validations` folder to define validation schemas for different request bodies.
- Added schemas for relevant request bodies (**e.g., signup, login**).
- Applied the **validation middleware** to routes to ensure that incoming requests are validated.
- Verified that each route uses the appropriate **validation schema** for its request body.
- Installed Zod package via `npm install zod`.
- …

Backend : zod validation for bodies of all requestes

---

backend/src/schema/signup-schema.ts
backend/src/services/implementation/auth.service.ts

Had a problem with the validation of registration request body.
The username was getting validated instead of name. 
Now I have implemented regex for validating name.

fix: fixed zod validation for name

---

frontend/src/components/user/common/BlogCard.tsx
frontend/src/components/user/profile/ProfileFeed.tsx

feat: list blogs in profile feed

---

backend/src/controllers/implementation/auth.controller.ts
backend/src/models/implementation/user.model.ts
backend/src/schema/signin.schema.ts
backend/src/services/implementation/auth.service.ts
backend/src/services/interface/IAuthService.ts
shared/types/index.ts

fixes in authentication

---

backend/src/configs/env.config.ts
backend/src/controllers/implementation/auth.controller.ts
backend/src/index.ts
backend/src/schema/signin.schema.ts
backend/src/schema/verify-otp.schema.ts
backend/src/services/implementation/auth.service.ts
backend/src/utils/generate-otp.util.ts
backend/src/utils/send-email.util.ts
backend/src/utils/validate-env.util.ts
package-lock.json

- Updated OTP type from number to string for consistency.
- Fixed issue where OTPs longer than 6 digits were being generated.
- Modified schema, service, and utility files to strictly enforce a 6-digit OTP.

fix: change OTP to string and fixed OTP length issue

---

frontend/src/components/user/common/AppSidebar.tsx

Implement collapsible=icon in ShadCN Sidebar to allow the sidebar to collapse while keeping icons visible

fix: Implement collapsible=icon in ShadCN Sidebar to allow the sidebar to collapse while keeping icons visible

---

backend/src/controllers/implementation/auth.controller.ts
backend/src/controllers/interface/IAuthController.ts
backend/src/routers/auth.router.ts
backend/src/services/implementation/auth.service.ts
backend/src/services/interface/IAuthService.ts

**Description**
Endpoint for refresh token created in both service layer and controller layer. Also called the method in the routes module.

feat: Refresh token function created

---

frontend/src/services/profileService.ts

Added profile service for api fetching.

Profile service

---

backend/src/constants/response-message.constant.ts
backend/src/controllers/implementation/auth.controller.ts
backend/src/controllers/implementation/profile.controller.ts
backend/src/controllers/interface/IAuthController.ts
backend/src/controllers/interface/IProfileController.ts
backend/src/index.ts
backend/src/models/implementation/user.model.ts
backend/src/repositories/implementation/user.repository.ts
backend/src/repositories/interface/IUserRepository.ts
backend/src/routers/auth.router.ts
backend/src/routers/profile.router.ts
backend/src/schema/update-profile.schema.ts
backend/src/services/implementation/auth.service.ts
backend/src/services/implementation/profile.service.ts
backend/src/services/interface/IAuthService.ts
backend/src/services/interface/IProfileService.ts
shared/types/index.ts

- Get Profile: Fetches user profile details.
- Update Profile Details: Allows users to update their profile information.
- Edit Username: Moved the existing username update logic from its previous file to the profile module for better organization.
- Implemented GET /profile API endpoint.
- Added PUT /update-profile API for updating profile details.
- Refactored profile-related services for better maintainability.
- Restructured the routing logic in the main backend file for improved organization and scalability.
@shreedev44 Please review the changes and let me know if any improvements are needed.

feat(profile): Add get profile & update profile details, allow username edit

---

frontend/src/services/blogServices.ts

Blog Service

---

frontend/src/components/user/landingPage/Contributors.tsx
frontend/src/components/user/profile/ProfileInfo.tsx
frontend/src/pages/landingPage/LandingPage.tsx
frontend/src/services/profileService.ts
frontend/src/store/blogSlice.ts

Add Contributors section in home page

add contributors section

---

backend/src/constants/response-message.constant.ts
backend/src/controllers/implementation/profile.controller.ts
backend/src/controllers/interface/IProfileController.ts
backend/src/middlewares/upload.middleware.ts
backend/src/repositories/implementation/user.repository.ts
backend/src/repositories/interface/IUserRepository.ts
backend/src/routers/profile.router.ts
backend/src/services/implementation/auth.service.ts
backend/src/services/implementation/profile.service.ts
backend/src/services/interface/IProfileService.ts
backend/src/utils/cloudinary.util.ts
backend/src/utils/generate-nanoid.ts
backend/src/utils/send-email.util.ts

**Description**
I have added change profile picture route on profile controller, profile service. The new image will be uploaded to Cloudinary and if there is existing image, The image will be deleted from Cloudinary.

feat: added change-profile-picture route

---

frontend/src/components/user/profile/ProfileInfo.tsx
frontend/src/router/AppRoutes.tsx
frontend/src/router/ProtectedRoutes.tsx

This pull request includes the following improvements:
- Added default profile image: Users without an uploaded profile picture now see a clean default avatar.
- Implemented protected routes: Certain pages are now accessible only to authenticated users.
- Added social links: Integrated social media links into the user profile page for better connectivity.
These changes enhance user experience, improve app security, and enrich the profile page's functionality.

Frontent: Default Image, Protected Routes, and Social Links

---

frontend/index.html
frontend/src/App.tsx
frontend/src/components/user/auth/SideLayout.tsx
frontend/src/components/user/common/Navbar.tsx
frontend/src/components/user/common/ThemeToggle.tsx
frontend/src/components/user/landingPage/LandingMenuBar.tsx
frontend/src/layouts/AppLayout.tsx
frontend/src/pages/community/Community.tsx
frontend/src/router/AppRoutes.tsx
frontend/src/router/ProtectedRoutes.tsx
frontend/src/router/UnProtectedRoutes.tsx

- Resolved theme persistence issue:
- Moved ThemeProvider from `Applayout.jsx` to `App.jsx` to ensure global theme control.
- Updated Community page:
- Added WhatsApp community link.
- Changed "Meet Our Core Team" to "Developer Team".
- Updated Notion link for current project.
- Improved Landing page menubar:
- Added missing theme toggle button.
- Updated logo in landing menubar page and also added theme switching support.
- Added protected route for Home page as per requirements.
- Added UnProtectedRoute to prevent logged-in users from accessing the auth page.
- Favicon changed but theme-based switching for favicon is still pending.
- Logo in auth pages updated (theme switching not needed there).

Fix theme persistence, update Community page, landing page UI, protect Home page and add unprotected Route

---

backend/.env.example
readme.md

This PR includes the following changes:
1.   Updated README.md to document required environment variables and setup instructions for .env configuration.
2.  Added .env.example file to serve as a reference for contributors to create their own .env file.
These additions improve onboarding for new contributors and clarify environment setup requirements.

docs: update README and add .env.example for environment configuration

---

frontend/src/components/user/auth/FormLayout.tsx
frontend/src/components/user/auth/SideLayout.tsx
frontend/src/components/user/auth/user-auth-form.tsx
frontend/src/components/user/common/password-input.tsx
frontend/src/hooks/userTab.ts
frontend/src/pages/auth/Auth.tsx

Fixed logo position in authentication page

---

backend/src/configs/env.config.ts
backend/src/schema/update-profile.schema.ts
frontend/src/components/user/editProfile/UpdateProfile.tsx
frontend/src/schemas/userSchema.ts

This PR fixes the issue where users could update their profile name to invalid or meaningless values like "--" (Reported in Issue #201). I have updated both backend and frontend validation to align with industry-standard practices (similar to platforms like Twitter, Facebook, and Instagram).
**Changes Made:**
Backend:
- Updated existing validation logic for username and bio.
- Added stricter checks to reject invalid or ambiguous names such as "--", empty spaces, and other non-meaningful inputs.
Frontend:
- Created a new file userSchema.ts for user profile update validation.
- Added validation rules for name and bio matching backend logic.
- If validation fails, a clear toast error message is displayed to inform the user.
**Improvements:**
- Prevents users from setting profile names to …

Fixed Profile Name Validation Issue (#201)

---

frontend/src/components/user/blogpost/viewBlog/ViewBlog.tsx
frontend/src/components/user/blogpost/viewBlog/blog.css

Fixed the issue in text color for the code block in blog (light mode)

Fix: text color issue in blog light mode

---

backend/src/configs/redis.config.ts
backend/src/index.ts
backend/src/middlewares/verify-token.middleware.ts
backend/src/types/express.d.ts
backend/src/types/jwt-payload.ts
backend/src/utils/jwt.util.ts
frontend/src/App.tsx
frontend/src/components/user/feeds/Feed.tsx
frontend/src/main.tsx
frontend/src/store/authStore.ts

changed the server start and connect DBs Asynchronously

chore: changed the server start and connect DBs Asynchronously

---

backend/src/controllers/implementation/auth.controller.ts
backend/src/index.ts
backend/src/middlewares/error.middlware.ts
backend/src/middlewares/verify-token.middleware.ts
backend/src/services/implementation/auth.service.ts
backend/src/types/jwt-payload.ts
backend/src/utils/jwt.util.ts
frontend/src/App.tsx
frontend/src/components/user/auth/user-auth-form.tsx
frontend/src/components/user/common/SearchBar.tsx
frontend/src/components/user/feeds/BlogActionBar.tsx
frontend/src/components/user/feeds/Feed.tsx
frontend/src/components/user/profile/ProfileFeed.tsx
frontend/src/config/axios.ts
frontend/src/layouts/AppLayout.tsx
frontend/src/pages/profile/editProfile.tsx
frontend/src/router/AppRoutes.tsx
frontend/src/router/ProtectedRoutes.tsx
frontend/src/router/UnProtectedRoutes.tsx
frontend/src/store/authStore.ts

Fixed an issue where Expired Refresh Token is not automatically refreshed

fix: Expired Access token not Refreshing

---

backend/src/controllers/implementation/blog.controller.ts
backend/src/controllers/interface/IBlogController.ts
backend/src/models/implementation/blog.model.ts
backend/src/repositories/implementation/blog.repository.ts
backend/src/repositories/interface/IBlogRepository.ts
backend/src/routers/blog.router.ts
backend/src/services/implementation/blog.service.ts
backend/src/services/interface/IBlogService.ts
frontend/src/components/user/blogpost/viewBlog/ViewBlogActionBar.tsx
frontend/src/components/user/comment/CommentSection.tsx
frontend/src/components/user/feeds/BlogActionBar.tsx
frontend/src/components/user/feeds/Feed.tsx
frontend/src/components/user/profile/ProfileFeed.tsx
frontend/src/services/blogServices.ts
frontend/src/store/blogStore.ts
frontend/src/types/index.ts
shared/types/index.ts

- Implements blog archiving support in both backend and frontend:
- Adds an archived field to the IBlog interface.
- Updates blog-fetching APIs to exclude archived blogs for non-owners.
- Adds archive/unarchive actions for blog authors.
- Integrates archived blogs under the "Archives" tab in the profile feed.
Impact
- Archived blogs are only visible to their authors.
- Non-archived blogs are shown by default in all public views.

feat: add blog archiving feature to backend and update frontend

---

frontend/src/components/user/blogpost/viewBlog/ViewBlog.tsx
frontend/src/components/user/blogpost/viewBlog/ViewBlogActionBar.tsx
frontend/src/components/user/common/BlogCardDropdown.tsx
frontend/src/components/user/feeds/BlogActionBar.tsx
frontend/src/components/user/feeds/Feed.tsx
frontend/src/components/user/profile/ProfileFeed.tsx

feat: add BlogCardDropdown component

---

backend/src/constants/response-message.constant.ts
backend/src/controllers/implementation/follow.controller.ts
backend/src/controllers/interface/IfollowController.ts
backend/src/index.ts
backend/src/repositories/implementation/follow.repository.ts
backend/src/repositories/interface/IFollowRepository.ts
backend/src/routers/follow.router.ts
backend/src/services/implementation/follow.service.ts
backend/src/services/interface/IFollowService.ts
frontend/src/components/user/profile/ProfileInfo.tsx
frontend/src/components/user/profile/UserListModal.tsx
frontend/src/services/followServices.ts

* Implemented followers and following listing functionality on the user profile page.
* When a user clicks on the "Followers" or "Following" button, a modal displays a list of users accordingly.
* Each user in the list shows their name , user name , profile picture , and a button to follow back or unfollow as applicable.
* Users can click on any listed follower/following to navigate to their profile page.
* Both backend and frontend integration is completed:
* Backend aggregates follower/following data with user details.
* Frontend displays the list and handles interactions (follow/unfollow/navigation).

Followers & Followings Listing

---

frontend/package.json
frontend/src/components/ui/imageEditor.tsx
frontend/src/components/user/blogpost/ThumbnailUploader.tsx
package-lock.json

This PR implements an enhanced image editing feature requested in Issue #[252].
Changes:
- Added react-filerobot-image-editor library for robust image editing capabilities
- Created a reusable ImageEditor component that includes:
- Cropping with preset aspect ratios (1:1, 16:9, 9:16, 4:3)
- Rotation and zoom functionality
- Multiple image filters and effects
- Fine-tuning adjustments (brightness, contrast, saturation, etc.)
- Annotation tools for adding text and shapes
- Resize functionality with aspect ratio preservation
- Updated ThumbnailUploader component with an intuitive edit button
- Integrated the editor to seamlessly replace edited images
The editor provides several additional features beyond the original requirements:
- Filter application for creative image styling
- Text and …

Feature: Image editor
